[build-system]
requires = ["hatchling>=1.6.0"]
build-backend = "hatchling.build"

[project]
name = "urllib3-lts-py37"
version = "2024.37891"
description = "LTS Security release for urllib3 (CVE-2024-37891 Patch) for Python 3.7"
readme = "README.md"
requires-python = ">=3.7, <3.8"
license = "MIT"
authors = [{name = "OmniPKG", email = "security@omnipkg.dev"}]
classifiers = [
    "Programming Language :: Python :: 3.7",
    "Topic :: Security",
]
dependencies = [
    # Original deps from urllib3 2.0.7
    # (extracted from checking original setup.py/pyproject.toml)
]

[project.urls]
Homepage = "https://github.com/1minds3t/urllib3-lts"
