[build-system]
requires = ["hatchling>=1.6.0"]
build-backend = "hatchling.build"

[project]
name = "urllib3-lts-py37"
version = "2025.66471"
description = "LTS Security Backport for urllib3 (Python 3.7)"
readme = "README.md"
requires-python = ">=3.7, <3.8"
license = "MIT"
authors = [{name = "1minds3t", email = "1minds3t@proton.me"}]
classifiers = [
    "Programming Language :: Python :: 3.7",
    "Topic :: Security",
]
dependencies = []

[project.urls]
Homepage = "https://github.com/1minds3t/urllib3-lts"
