[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "urllib3-lts"
version = "2025.66471"
description = "LTS Security Ecosystem for urllib3 (Fixes DoS, Redirects, Leaks)"
readme = "README.md"
requires-python = ">=3.7"
license = "MIT"
authors = [{name = "1minds3t", email = "1minds3t@proton.me"}]
dependencies = [
    "urllib3-lts-py37==2025.66471 ; python_version >= '3.7' and python_version < '3.8'",
    "urllib3-lts-py38==2025.66471 ; python_version >= '3.8' and python_version < '3.9'",
    "urllib3>=2.3.0 ; python_version >= '3.9'" 
]

[project.urls]
Homepage = "https://github.com/1minds3t/urllib3-lts"
